<?php

namespace AppBundle\Repository;

/**
 * DemandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandsRepository extends \Doctrine\ORM\EntityRepository
{
}
