<?php

namespace AppBundle\Repository;

/**
 * FlevaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlevaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
