<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;


/**
 * FreelancerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreelancerRepository extends \Doctrine\ORM\EntityRepository
{

    public function sortFreelancersByAcceptedProjects() : array
    {
    	$freelancersByAcceptedProject = $this->createQueryBuilder('demands')
										    	->select('freelancer.firstname,freelancer.lastname,COUNT(demands.id) as NumberofData')
										    	->from('AppBundle\Entity\Demands','demands')
										    	->join('demands.freelancer','freelancer')
										    	->where('demands.demandstatus = :demandstatus')
										    	->groupby('freelancer.id')
										    	->orderBy('NumberofData','DESC')
										    	->setParameter('demandstatus', 1)
										    	->getQuery()
										    	->getResult();

    	return $freelancersByAcceptedProject; 

    }

	public function sortFreelancerByReputation() : array
	{
		$freelancersByReputation = $this->createQueryBuilder('flevaluation')
										    	->select('freelancer.id,freelancer.firstname,freelancer.lastname,COUNT(flevaluation.mark) AS NumberofData ')
										    	->from('AppBundle\Entity\Flevaluation','flevaluation')
										    	->join('flevaluation.freelancer','freelancer')
										    	->groupby('freelancer.id')
										    	->orderBy('NumberofData','DESC')
										    	->getQuery()
										    	->getResult();

    	return $freelancersByReputation; 

	}    
}
