<?php

namespace AppBundle\Repository;

/**
 * JoevaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoevaluationRepository extends \Doctrine\ORM\EntityRepository
{
}
