<?php

namespace AppBundle\Repository;

/**
 * TestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestsRepository extends \Doctrine\ORM\EntityRepository
{
}
