app:
    resource: '@AppBundle/Controller/'
    type: annotation
app_jobowner:
    resource: "@AppBundle/Resources/config/routing/jobowner.yml"
    prefix:   /jobowner
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
jobowner_examen:
    resource: "@AppBundle/Resources/config/routing/examen.yml"
    prefix:   /examens