jobowner_index:
    path:     /
    defaults: { _controller: "AppBundle:Jobowner:index" }
    methods:  GET

jobowner_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Jobowner:show" }
    methods:  GET

jobowner_new:
    path:     /new
    defaults: { _controller: "AppBundle:Jobowner:new" }
    methods:  [GET, POST]

jobowner_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Jobowner:edit" }
    methods:  [GET, POST]

jobowner_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Jobowner:delete" }
    methods:  DELETE
